<?php

declare(strict_types=1);

require_once dirname(__DIR__) . '/config/Config.php';

/**
 * Database
 *
 * PDO wrapper for StreamHive. One shared connection (singleton) is reused for
 * the whole request, so individual models never open their own connection.
 * Every query runs through prepared statements via query().
 */
class Database
{
    /**
     * The single shared instance.
     */
    private static ?Database $instance = null;

    /**
     * The underlying PDO connection.
     */
    private PDO $connection;

    /**
     * Private constructor: build the DSN from the .env values and connect.
     * Callers use Database::getInstance() instead.
     */
    private function __construct()
    {
        $host = Config::get('DB_HOST', '127.0.0.1');
        $port = Config::get('DB_PORT', '3306');
        $name = Config::get('DB_NAME', '');
        $user = Config::get('DB_USER', '');
        $password = Config::get('DB_PASS', '');

        $dsn = "mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4";

        $options = [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ];

        $this->connection = new PDO($dsn, $user, $password, $options);
    }

    /**
     * Return the shared Database instance, creating it on first use.
     */
    public static function getInstance(): Database
    {
        if (self::$instance === null)
        {
            self::$instance = new self();
        }

        return self::$instance;
    }

    /**
     * Run a prepared statement and return the executed PDOStatement.
     *
     * @param string                   $sql    SQL with named or positional placeholders.
     * @param array<int|string, mixed> $params Values bound to those placeholders.
     */
    public function query(string $sql, array $params = []): PDOStatement
    {
        $statement = $this->connection->prepare($sql);
        $statement->execute($params);

        return $statement;
    }

    /**
     * Return the id generated by the most recent INSERT.
     */
    public function lastInsertId(): int
    {
        return (int) $this->connection->lastInsertId();
    }
}
